spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/webpro
        username: root
        password:
#        url: jdbc:mjutask-db.c5tjoxciejrk.ap-northeast-2.rds.amazonaws.com:3306/webpro
#        username: admin
#        password: mjutask0131
    jpa:
        hibernate:
            ddl-auto: update
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    jwt:
        secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWp1bm8tc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWp1bm8tYXBwbGluZwo=
        access-token-validity-in-seconds: 360000 #100시간
        refresh-token-validity-in-seconds: 2592000 #30일
        access:
            expiration: 100
            header: Authorization
        refresh:
            expiration: 200
            header: Authorization-refresh
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 535321350238-hah6c37spl3eua2bujvvoug3ql237nns.apps.googleusercontent.com
                        redirect-uri: http://localhost:8080/login/oauth2/code/google
                        client-secret: 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
                        client-name: Google
                        scope:
                            - email
                            - profile
    data:
        redis:
            host: 127.0.0.1
            port: 6379
springdoc:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    api-docs:
        groups:
            enabled: true
    swagger-ui:
        operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
        tags-sorter: alpha # 태그 정렬 기준
        path: /swagger-ui.html # html 문서 접속 경로
        disable-swagger-default-url: true
        display-query-params-without-oauth2: true
        doc-expansion: none # tag, operation 펼치는 방식
    paths-to-match:
        - /**

imp:
    code: imp26662343

    api:
        key: 6253657173615713
        secretkey: gnEeycSMuHapzP4B1PiDJtSUTFk6jW6dKz8fb99kvIyF5cMlJsSj4PFNC4judYDKvJEA12UYIeuGR8bU